In [2]:
import os
import warnings

import geopandas as gpd
import matplotlib.pyplot as plt
import nivapy3 as nivapy

plt.style.use("ggplot")
warnings.simplefilter("ignore")

## Delineate catchment boundaries for coastal drainage basins

Delineate catchment boundaries for each outlet identified in the previous notebook.

In [3]:
# User input

# Directory to read raw shapefile from and to write processed shp to
cur_dir = r"/home/jovyan/shared/common/norsink/spatial/coastal_drainage_basins"

# Smallest catchments for delineation. Used to snap outlet co-ordinates to the flow
# accumulation grid to improve catchment delineation
min_size_km2 = 1.0

In [5]:
# Read in outlets
outlet_gdf = gpd.read_file(os.path.join(cur_dir, "shp", "outlets_all.shp"))
outlet_df = outlet_gdf[["elvid", "nbfVassNr", "easting", "northing", "latitude", "longitude"]]
outlet_df.head()

   elvid nbfVassNr       easting      northing   latitude  longitude
0      0   022.32Z  57644.761863  6.455798e+06  58.022290   7.502217
1      1   022.43Z  51780.981208  6.457149e+06  58.028450   7.401257
2      2    022.3Z  64044.032832  6.457637e+06  58.044984   7.606244
3      6    022.4Z  52223.007045  6.459131e+06  58.046539   7.404913
4     10   023.22Z  34091.759523  6.456831e+06  58.007450   7.105193

In [20]:
# Catchment boundaries and areas
cat_gdf = nivapy.spatial.derive_watershed_boundaries(
    outlet_df,
    id_col="elvid",
    xcol="easting",
    ycol="northing",
    crs=f"epsg:{epsg}",
    min_size_km2=min_size_km2,
    dem_res_m=40,
    reproject=True,
)
cat_gdf["area_km2"] = cat_gdf.to_crs({"proj": "cea"})["geometry"].area / 1e6

Connection successful.

Looping over vassdragsområder:   0%|          | 0/236 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 001:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 002:   0%|          | 0/14 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 003:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 004:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 005:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 006:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 007:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 008:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 009:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 010:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 011:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 012:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 013:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 014:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 015:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 016:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 017:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 018:   0%|          | 0/17 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 019:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 020:   0%|          | 0/16 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 021:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 022:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 023:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 024:   0%|          | 0/19 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 025:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 026:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 027:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 028:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 029:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 030:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 031:   0%|          | 0/13 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 032:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 033:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 035:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 036:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 037:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 038:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 039:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 041:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 042:   0%|          | 0/21 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 043:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 044:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 045:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 046:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 047:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 048:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 049:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 050:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 051:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 052:   0%|          | 0/19 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 053:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 054:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 055:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 056:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 057:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 059:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 060:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 061:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 062:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 063:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 064:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 065:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 066:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 067:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 068:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 069:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 070:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 071:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 072:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 073:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 074:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 075:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 076:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 077:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 078:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 079:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 080:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 081:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 082:   0%|          | 0/20 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 083:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 084:   0%|          | 0/17 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 085:   0%|          | 0/13 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 086:   0%|          | 0/22 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 087:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 088:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 089:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 090:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 091:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 092:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 093:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 094:   0%|          | 0/19 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 095:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 096:   0%|          | 0/17 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 097:   0%|          | 0/17 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 098:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 099:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 100:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 101:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 102:   0%|          | 0/16 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 103:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 104:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 105:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 106:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 107:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 108:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 109:   0%|          | 0/14 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 110:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 111:   0%|          | 0/13 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 112:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 113:   0%|          | 0/16 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 114:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 115:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 116:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 117:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 118:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 119:   0%|          | 0/18 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 120:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 121:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 122:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 123:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 124:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 125:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 126:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 127:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 128:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 129:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 130:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 131:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 132:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 133:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 134:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 135:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 136:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 137:   0%|          | 0/17 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 138:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 139:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 140:   0%|          | 0/17 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 141:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 142:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 143:   0%|          | 0/25 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 144:   0%|          | 0/16 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 145:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 146:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 147:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 148:   0%|          | 0/15 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 149:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 150:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 151:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 152:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 153:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 154:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 155:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 156:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 157:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 158:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 159:   0%|          | 0/240 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 160:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 161:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 162:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 163:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 164:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 165:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 166:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 167:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 168:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 169:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 170:   0%|          | 0/14 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 171:   0%|          | 0/14 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 172:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 173:   0%|          | 0/12 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 174:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 175:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 176:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 177:   0%|          | 0/17 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 178:   0%|          | 0/27 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 179:   0%|          | 0/25 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 180:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 181:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 184:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 185:   0%|          | 0/40 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 186:   0%|          | 0/19 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 187:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 188:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 189:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 190:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 191:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 193:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 194:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 195:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 196:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 197:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 198:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 199:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 200:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 202:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 203:   0%|          | 0/13 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 204:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 205:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 206:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 207:   0%|          | 0/1 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 208:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 209:   0%|          | 0/9 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 210:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 211:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 212:   0%|          | 0/10 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 213:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 215:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 216:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 217:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 218:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 220:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 222:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 223:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 224:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 225:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 226:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 227:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 228:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 229:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 230:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 231:   0%|          | 0/8 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 232:   0%|          | 0/2 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 233:   0%|          | 0/7 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 234:   0%|          | 0/11 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 235:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 236:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 237:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 238:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 239:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 240:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 241:   0%|          | 0/5 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 242:   0%|          | 0/3 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 243:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 244:   0%|          | 0/4 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 246:   0%|          | 0/6 [00:00<?, ?it/s]

Looping over outlets in vassdragsområder 247:   0%|          | 0/8 [00:00<?, ?it/s]

In [21]:
cat_gdf.head()

,elvid,geometry,nbfVassNr,easting,northing,latitude,longitude,area_km2
0,0,"POLYGON ((58200 6456760, 58200 6456720, 58120 ...",022.32Z,57644.761863,6.455798e+06,58.022290,7.502217,1.231893
1,1,"MULTIPOLYGON (((52000 6457680, 52000 6457640, ...",022.43Z,51780.981208,6.457149e+06,58.028450,7.401257,10.104939
2,2,"MULTIPOLYGON (((66200 6458160, 66200 6458120, ...",022.3Z,64044.032832,6.457637e+06,58.044984,7.606244,39.289173
3,6,"POLYGON ((54960 6466240, 54960 6466200, 54720 ...",022.4Z,52223.007045,6.459131e+06,58.046539,7.404913,22.756594
4,10,"POLYGON ((32400 6460240, 32400 6460200, 32360 ...",023.22Z,34091.759523,6.456831e+06,58.007450,7.105193,5.794413

In [22]:
# Save shapefiles with catchments for all rivers
cat_gdf.to_file(os.path.join(output_dir, "shp", "catchments_all.shp"))

In [23]:
cat_gdf.describe()

,elvid,easting,northing,latitude,longitude,area_km2
count,2079.000000,2.079000e+03,2.079000e+03,2079.000000,2079.000000,2079.000000
mean,3645.810967,3.259435e+05,7.170180e+06,64.499918,12.103370,136.392562
std,1749.969224,2.845742e+05,4.147529e+05,3.765223,6.108677,1161.987810
min,0.000000,-5.181612e+04,6.455798e+06,58.007450,4.907914,1.001494
25%,2517.500000,6.038513e+04,6.823440e+06,61.239533,6.810190,8.183080
50%,3761.000000,3.114923e+05,7.138097e+06,64.310389,11.216865,17.908941
75%,5141.500000,4.961911e+05,7.532250e+06,67.901020,14.907800,42.906004
max,6278.000000,1.105239e+06,7.934980e+06,71.063165,31.014342,41797.108822